name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

env:
  XCODE_VERSION: '13.4.1'
  JAVA_VERSION: '14'
  NODE_VERSION: '18'

jobs:
  ios:
    name: Test iosX64
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Run Test
        id: gradle-test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :iosX64Test

  mac:
    name: Test macOSX64
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Run Test
        id: gradle-test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :macosX64Test

  javascript:
    name: Test NodeJS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm install yarn

      - name: Run Test
        id: gradle-test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :jsNodeTest

  jvm:
    name: Test JVM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run Test
        id: gradle-test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :jvmTest

  linux:
    name: Test linuxX64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run Test
        id: gradle-test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :linuxX64Test

  windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run Test
        id: gradle-test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :mingwX64Test
