name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

env:
  XCODE_VERSION: '13.4.1'
  JAVA_VERSION: '14'
  NODE_VERSION: '18'

jobs:
  darwin:
    name: Test darwin
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

#      - name: Run ios(intel) tests
#        id: gradle-iosX64Test
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: :ofm:iosX64Test --stacktrace

#      - name: Run ios(apple silicon) tests
#        id: gradle-iosSimulatorArm64Test
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: :ofm:iosSimulatorArm64Test --stacktrace

      - name: Run macos(intel) tests
        id: gradle-macosX64Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :ofm:macosX64Test --stacktrace

      - name: Run macos(apple silicon) tests
        id: gradle-macosArm64Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :ofm:macosArm64Test --stacktrace

  jvm:
    name: Test JVM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run Test
        id: gradle-test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :ofm:jvmTest --stacktrace

  android:
    name: Test Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run Test
        id: gradle-test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :ofm:testReleaseUnitTest --stacktrace

  common:
    name: Test common
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run Test
        id: gradle-test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :ofm:test --stacktrace

  publish:
    name: Publish SNAPSHOT
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Clean
        id: gradle-clean
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean

      - name: Publish to Github Packages
        id: gradle-publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish