name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

env:
  XCODE_VERSION: '13.4.1'
  JAVA_VERSION: '14'

jobs:
  mac:
    name: Test macOSX64
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Run Test
        id: gradle-test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :cleanNativeTest :nativeTest

  linux:
    name: Test linuxX64
    runs-on: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run Test
        id: gradle-test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :cleanNativeTest :nativeTest

  android:
    name: Test android
    runs-on: android/android
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run Test
        id: gradle-test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :cleanJvmTest :jvmTest

#  build:
#    name: Build
#    runs-on: macos-12
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - uses: actions/setup-java@v1
#        with:
#          java-version: ${{ env.JAVA_VERSION }}
#
#      - uses: maxim-lobanov/setup-xcode@v1
#        with:
#          xcode-version: ${{ env.XCODE_VERSION }}
#
#      - name: Build Shared artifacts
#        id: gradle-build
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: :shared:build
