name: Build and Test

on:
  push:
    branches:
      - main
      - ci
    paths-ignore:
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

env:
  XCODE_VERSION: '13.4.1'
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'corretto'

jobs:
  macos:
    name: Build on macos
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Mac build
        run: |
          ./gradlew macosX64Test iosX64Test \
          publishKotlinMultiplatformPublicationToMavenLocal \
          publishIosArm32PublicationToMavenLocal \
          publishIosArm64PublicationToMavenLocal \
          publishIosSimulatorArm64PublicationToMavenLocal \
          publishIosX64PublicationToMavenLocal \
          publishMacosX64PublicationToMavenLocal \
          publishMacosArm64PublicationToMavenLocal \
          --no-daemon --stacktrace

  windows:
    name: Build on windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: JDK setup
        uses: actions/setup-java@v3
        with:
          java-version:  ${{ env.JAVA_VERSION }}
          distribution:  ${{ env.JAVA_DISTRIBUTION }}

      - name: Windows build
        run: |
          ./gradlew mingwX64Test publishKotlinMultiplatformPublicationToMavenLocal publishMingwX64PublicationToMavenLocal publishMingwX86PublicationToMavenLocal --no-daemon --stacktrace
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"

  linux:
    name: Build on linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Linux build
        run: |
          ./gradlew build publishToMavenLocal --no-daemon --stacktrace
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"

  publish:
    name: Publish SNAPSHOT
    runs-on: macos-12
    needs: [ linux, windows, macos ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Clean
        id: gradle-clean
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean

      - name: Publish to Github Packages
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        id: gradle-publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish